#ifndef COMMON_MACRO_H
#define COMMON_MACRO_H

#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICNAME 432
#define ERR_NICKNAMEINUSE 433
#define ERR_NICKCOLLISION 436
#define ERR_UNAVAILABLERESOURCE 437
#define ERR_NEEDMOREPARAMS 461
#define ERR_ALREADYREGISTERED 462
#define ERR_RESTRICTED 484


#endif
