#ifndef COMMON_MACRO_H
#define COMMON_MACRO_H


#define RPL_WELCOME				"1" //
#define RPL_YOURHOST			"2" //
#define RPL_CREATED				"3" //
#define RPL_MYINFO				"4" //
#define RPL_BOUNCE				"5"// 
#define RPL_NOTOPIC				"331"// 
#define RPL_TOPIC				"332"
#define RPL_NAMEREPLY			"353"
#define RPL_ENDOFNAMES  		"366"

#define ERR_NOSUCHNICK			"401"
#define ERR_NOSUCHCHANNEL		"403"
#define ERR_CANNOTSENDTOCHAN	"404"
#define ERR_TOOMANYCHANNELS		"405" 
#define ERR_TOOMANYTARGETS		"407" 
#define ERR_NORECIPIENT			"411"
#define ERR_NOTEXTTOSEND		"412"
#define ERR_NOTOPLEVEL			"413"
#define ERR_WILDTOPLEVEL		"414"
#define ERR_BADCHANMASK			"415"
#define ERR_UNKNOWNCOMMAND		"421"
#define ERR_NONICKNAMEGIVEN		"431"
#define ERR_ERRONEUSNICKNAME	"432"
#define ERR_NICKNAMEINUSE		"433"
#define ERR_NICKCOLLISION		"436"
#define ERR_UNAVAILABLERESOURCE "437"
#define ERR_NOTONCHANNEL		"442"
#define ERR_NEEDMOREPARAMS		"461"
#define ERR_ALREADYREGISTERED	"462"
#define ERR_CHANNELISFULL		"471"
#define	ERR_INVITEONLYCHAN		"473"
#define ERR_BANNEDFROMCHAN		"474"
#define ERR_BADCHANNELKEY		"475"
#define ERR_RESTRICTED			"484"


#endif
